dist: focal
sudo: required
language: node_js
node_js:
  - "22"

services:
  - docker

before_install: 
  # Remove Ruby from the environment (prevent Ruby-related errors)
  #- sudo apt-get remove -y ruby
  #- sudo apt-get autoremove -y
  - gem install nokogiri
  - gem install logger

  # Optional: Clean Docker cache to avoid old builds
  - docker system prune -f
  
  - docker build -t mpatal/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true mpatal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "frontend"
  env: "Frontend-env-1"
  bucket_name: "elasticbeanstalk-ca-central-1-337909763072"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


  