sudo: required
services:
  - docker

before_install: 
  - docker build -t mpatal/docker-react -f Dockerfile.dev .

  # Update Bundler to handle default gems correctly
  - gem install bundler
  - bundle update --bundler

  # Explicitly install the correct version of logger
  - gem install logger -v '~> 1.7'

script: 
  - docker run -e CI=true mpatal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "frontend"
  env: "Frontend-env-1"
  bucket_name: "elasticbeanstalk-ca-central-1-337909763072"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


  