name: Deploy Frontend
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use the access token here

      - name: Build and test
        run: |
          DOCKER_BUILDKIT=1 docker build --no-cache -t mpatal/react-test -f Dockerfile.dev .
          docker run -e CI=true mpatal/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: frontend-env
          existing_bucket_name: elasticbeanstalk-ca-central-1-${{ secrets.AWS_ACCOUNT_ID }}
          region: ca-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
